version: '3.4'

services:
   
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    
    volumes: 
        - ./DataLawyer.Infrastructure/_MySQL_Init_Script:/docker-entrypoint-initdb.d
    environment: 
        - MYSQL_ROOT_PASSWORD=D4taL4wy3r@
        - bind-adress=0.0.0.0

  datalawyer.api:
    build:
      context: .
      dockerfile: DataLawyer.API/Dockerfile
    
    ports:
        - "5000:80"
    environment:
        - DBHOST=mysql
        - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
       - mysql